project:
  type: website

website:
  title: "TH 的技術部落格"
  site-url: "https://cxweoth.github.io/tech-blog/"
  navbar:
    left:
      - text: 首頁
        href: index.qmd
      - text: 文章
        href: posts/index.qmd
      - text: 關於
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/cxweoth
      - icon: linkedin
        href: https://www.linkedin.com/in/tsung-hsuan-hung-79125190/

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    toc-title: "目錄"
    highlight-style: atom-one-dark
    code-fold: true
    code-tools: false
    number-sections: true
    fig-align: center
    fig-width: 8
    fig-height: 6
    fig-format: retina
    fig-dpi: 96
    fig-cap-location: bottom
    link-external-icon: true
    link-external-newwindow: true
    self-contained: true
    css: styles.css

execute:
  freeze: auto
  cache: true
  warning: false
  error: false
