project:
  type: website

website:
  title: "TH's Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/elman.qmd
        text: Elman 推導

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    highlight-style: atom-one-dark
    include-in-header: 
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css">
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js"
          onload="renderMathInElement(document.body, {delimiters: [{left: '$$', right: '$$', display: true}, {left: '$', right: '$', display: false}]});"></script>